# Generated by Django 5.0.14 on 2026-01-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_init_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_logo',
            field=models.BooleanField(default=False),
        ),
    ]
