# Generated by Django 5.0.14 on 2026-01-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications_relation', to='core.project')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specification')),
            ],
            options={
                'db_table': 'project_specification',
                'unique_together': {('project', 'specification')},
            },
        ),
    ]
