# Generated by Django 5.0.14 on 2026-01-17 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='svg_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='svg_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs_relation', to='core.project'),
        ),
    ]
