# Generated by Django 5.0.14 on 2026-03-02 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_framework_svg_url_specification_svg_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('git_url', models.CharField(max_length=255, null=True)),
                ('git_image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'contributor',
            },
        ),
        migrations.AlterField(
            model_name='specification',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('communicatie', 'Communicatie'), ('protocol', 'Protocol'), ('sensor', 'Sensor'), ('beveiliging', 'beveiliging'), ('interface', 'Interface'), ('dataformat', 'Dataformat'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors_relation', to='core.project')),
            ],
            options={
                'db_table': 'project_contributor',
                'unique_together': {('project', 'contributor')},
            },
        ),
    ]
